#!/usr/bin/perl
use strict;
use warnings;
use 5.010;

use File::Basename qw(dirname);
use Cwd qw(abs_path);

my $root;

BEGIN {
	$root = dirname( dirname( dirname( abs_path($0) ) ) );
}

use lib "$root/lib";

use Perl::Maven::DB;
my $db = Perl::Maven::DB->new("$root/pm.db");

my $stats = $db->stats;

# TODO remove hard-coded perl_maven_cookbook
my $code = 'perl_maven_cookbook';

if ( not @ARGV ) {

	say "all_the_users.value $stats->{all_users}";
	say 'verified_users.value ' . ( $stats->{all_users} - $stats->{not_verified} );
	say "not_verified_users.value $stats->{not_verified}";
	say "verified_but_no_password.value $stats->{no_password}";
	say "has_password.value $stats->{has_password}";
	say "new_password.value $stats->{new_password}";
	say "old_password.value $stats->{old_password}";
	say "$stats->{products}{$code}{code}.value $stats->{products}{$code}{cnt}\n";

	exit;
}

if ( $ARGV[0] eq 'config' ) {
	print <<'END_CONFIG';
graph_title Number of users
graph_vlabel sec
graph_category PerlMaven
END_CONFIG

	say 'all_the_users.label All the users';
	say 'verified_users.label Verified';
	say 'not_verified_users.label NOT Verified';
	say 'verified_but_no_password.label Verified but NO password';
	say 'has_password.label Has password';
	say 'new_password.label New password';
	say 'old_password.label Old password';
	say "$stats->{products}{$code}{code}.label $stats->{products}{$code}{code}";

	exit;
}

