#!/usr/bin/perl
use strict;
use warnings;
use 5.010;

use File::Basename qw(dirname);
use Cwd qw(abs_path);

my $root;

BEGIN {
	$root = dirname( dirname( dirname( abs_path($0) ) ) );
}

use lib "$root/lib";

use Perl::Maven::DB;
my $db = Perl::Maven::DB->new("$root/pm.db");

my $stats = $db->stats;

if ( not @ARGV ) {

	print "all_the_users.value $stats->{all_users}\n";
	print 'verified_users.value ' . ( $stats->{all_users} - $stats->{not_verified} ) . "\n";
	print "not_verified_users.value $stats->{not_verified}\n";
	print "verified_but_no_password.value $stats->{no_password}\n";
	say "has_password.value $stats->{has_password}";
	say "new_password.value $stats->{new_password}";
	say "old_password.value $stats->{old_password}";
	exit;
}

if ( $ARGV[0] eq 'config' ) {
	print <<"END_CONFIG";
graph_title Number of users
graph_vlabel sec
graph_category PerlMaven
END_CONFIG

	print "all_the_users.label All the users\n";
	print "verified_users.label Verified\n";
	print "not_verified_users.label NOT Verified\n";
	print "verified_but_no_password.label Verified but NO password\n";
	say "has_password.label Has password";
	say "new_password.label New password";
	say "old_password.label Old password";

	exit;
}

