#!/usr/bin/perl
use strict;
use warnings;

use File::Basename qw(dirname);
use Cwd            qw(abs_path);

my $root;

BEGIN {
	$root = dirname( dirname( dirname( abs_path($0) ) ) );
}

use lib "$root/lib";

use Perl::Maven::DB;
my $db = Perl::Maven::DB->new("$root/pm.db");

my $day            = time - 60 * 60 * 24;
my $week           = time - 60 * 60 * 24 * 7;
my ($new_verify_1) = $db->{dbh}->selectrow_array( 'SELECT COUNT(*) FROM user WHERE verify_time > ?',   undef, $day );
my ($new_verify_7) = $db->{dbh}->selectrow_array( 'SELECT COUNT(*) FROM user WHERE verify_time > ?',   undef, $week );
my ($new_users_1)  = $db->{dbh}->selectrow_array( 'SELECT COUNT(*) FROM user WHERE register_time > ?', undef, $day );
my ($new_users_7)  = $db->{dbh}->selectrow_array( 'SELECT COUNT(*) FROM user WHERE register_time > ?', undef, $week );

if ( not @ARGV ) {
	print "new_users_1.value $new_users_1\n";
	print "new_users_7.value $new_users_7\n";
	print "new_verified_users_1.value $new_verify_1\n";
	print "new_verified_users_7.value $new_verify_7\n";
	exit;
}

if ( $ARGV[0] eq 'config' ) {
	print <<"END_CONFIG";
graph_title Number of new users
graph_vlabel cnt
graph_category PerlMaven
END_CONFIG

	print "new_users_1.label Registered in last 24 hours\n";
	print "new_users_7.label Registered in last 7 days\n";
	print "new_verified_users_1.label Verified first e-mail in last 24 hours\n";
	print "new_verified_users_7.label Verified first e-mail in last 7 days\n";
	exit;
}

