domains:
  'test-pm.com':
    dbfile: 'test_abc.db'
    free_product: 'some_free_product'
    main_site: en
      #redirect: 0
    www:
      redirect: 'https://test-pm.com/'
    root: 'test'
    meta: 'meta'
    conf:
      show_newsletter_form: 0
    title: 'Test Maven'
    series: 0
    from: '<test@perlmaven.com>'
    feed_size: 2
    feeds:
      __main__:
        description: "Test description for feed"
        subtitle: A show about Perl and Perl users
        copyright: 2014 Gabor Szabo
        author: Gabor Szabo
        image:  https://code-maven.com/img/code_maven_128.png
        keywords:
          - 'code-maven'
          - 'open source'
          - 'software'
          - 'development'
          - 'news'
    admin:
      email: 'Test Maven <admin-test@perlmaven.com>'
    dirs:
      img: 'images'
    sites:
      test-pm.com:
        conf:
          show_newsletter_form: 1
        dirs:
          download: 'download'
          pro: 'pro'
